--DROP TABLE users IF EXISTS;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  activity VARCHAR(200),
  start_planned  VARCHAR(250),
  start_actual VARCHAR(250),
  finish_planned VARCHAR(250),
  finish_actual VARCHAR(250),
  status VARCHAR(100),

);